services:
  - type: web
    name: labms-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: zbackend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_HOST
        fromDatabase:
          name: labms-mysql
          property: host
      - key: DB_PORT
        fromDatabase:
          name: labms-mysql
          property: port
      - key: DB_NAME
        fromDatabase:
          name: labms-mysql
          property: database
      - key: DB_USER
        fromDatabase:
          name: labms-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: labms-mysql
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://labms-a8a5xj2w5-subashs-projects-d775d590.vercel.app
    
    autoDeploy: true

databases:
  - name: labms-mysql
    databaseName: labms_db
    user: labms_user
    plan: free
    region: oregon
